#pragma once

typedef enum {
    AGENT_STATE_IDLE,
    AGENT_STATE_RUN_LEFT,
    AGENT_STATE_RUN_RIGHT,
    AGENT_STATE_JUMP,
    AGENT_STATE_DYING,
    AGENT_STATE_DEAD,
    AGENT_STATE_COUNT,
} AgentStateId;
